# This is comments
# [START app_yaml]
runtime: nodejs
env: flex

# [START network]
# This ensures clients will be able to connect via websockets to any instance of
# this app using websockets
network:
  forwarded_ports:
  - 65080
  instance_tag: websocket
# [END network]
# [END app_yaml]

# Temporary setting to keep gcloud from uploading node_modules
skip_files:
 - ^node_modules
